name: my-site

services:
  server:
    image: hugomods/hugo:exts
    command: hugo server --bind 0.0.0.0 --poll 700ms
    volumes:
      - $PWD:/src
      - $USERPROFILE/hugo_cache:/tmp/hugo_cache
    ports:
      - 1313:1313